config/routes.rb
PatebinClone::Application.routes.draw do
  root :to => "web#index"
  get "posts/show"
  get "users/new"
  get "web/new"
  get "users/login"
  get "users/logout"
  get "web/index"
  get "web/login"
  get "web/logout"
  post "users/login_attempt"

  resources :web
  resources :posts
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :name, :presence => true
	validates :paste_content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..20, :on => :create

	before_save :encrypt_password
	after_save :clear_password

	def encrypt_password
		if password.present?
			self.encrypted_password = BCrypt::Password.create(password)
		end
	end

	def clear_password
		self.password = nil
	end

	def self.authenticate(username="", login_password="")
		user = User.find_by_username(username)

		if user && user.match_password(login_password)
			return user
		else
			return false
		end
	end   

	def match_password(login_password="")
	    BCrypt::Password.new(encrypted_password) == login_password
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 
			def authenticate_user
				unless session[:user_id]
					redirect_to(:controller => 'web', :action => 'login')
					return false
				else
					# set current user object to @current_user object variable
					@current_user = User.find session[:user_id] 
					return true
				end
			end

			def read_user
				if session[:user_id]
					# set current user object to @current_user object variable
					@current_user = User.find session[:user_id] 
				end
				return true
			end

			def save_login_state
				if session[:user_id]
					redirect_to(:controller => 'web')
					return false
				else
					return true
				end
			end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
  	@post = Post.find(params[:id])
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		flash[:notice] = "You Paste successfully"
  		flash[:color] = "valid"
  		redirect_to @post
  	else
  		flash[:notice] = "Form is invalid"
  		flash[:color] = "invalid"
  		redirect_to new_web_path(:post => @post)
  	end
  end

  private
    def post_params
      params.require(:post).permit(:name, :user, :paste_content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :save_login_state, :only => [:new, :create]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "You Signed up successfully"
  		flash[:color] = "valid"
      redirect_to(:controller => 'web', :action => 'index')
  	else
  		flash[:notice] = "Form is invalid"
  		flash[:color] = "invalid"
      render "new"
  	end
  end

  def login_attempt
  	authorized_user = User.authenticate(params[:username], params[:password])
  	if authorized_user
  		session[:user_id] = authorized_user.id
  		flash[:notice] = "Wow Welcome again, you logged in as #{authorized_user.username}"
  		redirect_to(:controller => 'web', :action => 'index')
  	else
  		flash[:notice] = "Invalid Username or Password"
  		flash[:color]= "invalid"
  		redirect_to(:controller => 'web', :action => 'login')
  	end
  end

  def logout
	 session[:user_id] = nil
	 redirect_to :controller => 'web', :action => 'index'
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/web_controller.rb
class WebController < ApplicationController
  before_filter :authenticate_user, :only => [:profile, :setting]
  before_filter :save_login_state, :only => [:login, :login_attempt]
  before_filter :read_user
  def index
    @posts = Post.all
  end

  def new
    if !params[:post]
      @post = Post.new
    else 
      @post = params[:post]
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/web_helper.rb
module WebHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatebinClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="page">
  <% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/show.html.erb
<h1>Paste Bin - Show</h1>

<p>
  <b>Name :</b>
  <%= @post.name %>
</p>

<p>
  <b>Paste Content :</b><br>
  <%= @post.paste_content %>
</p>

<p>
  <b>By :</b>
  <%= @post.user %>
</p>

<%= link_to "Back to home page", web_index_path %>

app/views/users/new.html.erb
<% @page_title = "Paste Bin | Signup" -%>
	<div class="Sign_Form">
		<h1>Paste Bin - Sign Up</h1>
		<%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
			<p>Username:</br> <%= f.text_field :username %> </p>
			<p>Email:</br> <%= f.text_field :email%> </p>
			<p>Password:</br> <%= f.password_field :password %></p>
			<p>Password Confirmation:</br> <%= f.password_field :password_confirmation %> </p>
			<%= f.submit :Signup %>
		<% end %>

		<% if @user.errors.any? %>
			<ul class="Signup_Errors">
				<% for message_error in @user.errors.full_messages %>
					<li>* <%= message_error %></li>
				<% end %>
			</ul>
		<% end %>
	</div>
	<br>
	<%= link_to "Back to home page", web_index_path %>

app/views/web/index.html.erb
<h1>Paste Bin</h1>

<% if !session[:user_id] %>
<%= link_to "Login", web_login_path %>
<%= link_to "Registeration", new_user_path %>
<% else %>
<p>Welcome, <%=@current_user.username%></p>
<%= link_to "Logout", users_logout_path %>
<% end %>

<h2>Listing Pastes</h2>
<%= link_to "Create new Pastebin", new_web_path %>
 
<table>
  <tr>
    <th>Paste Name</th>
    <th>By User</th>
    <th>Actions</th>
  </tr>
 
<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.user %></td>
    <td><%= link_to 'Show', post %></td>
  </tr>
<% end %>
</table>

app/views/web/login.html.erb
<% @page_title = "Paste Bin | Login" -%>
<div class= "Login_Form">
	<h1>Paste Bin - Login</h1>
	<%= form_tag(:controller => 'users', :action => 'login_attempt') do %>
		<p>Username: <%= text_field_tag(:username) %></p> 
		<p>Password: <%= password_field_tag :password %></p> 
	 	<%= submit_tag("Log In") %>
	<% end %>
</div>
<%= link_to "Back to home page", web_index_path %>

app/views/web/new.html.erb
<% @page_title = "Paste Bin | New Post" -%>
<div class= "New_Post_Form">
	<h1>Paste Bin - New Paste</h1>
	<%= form_for(:post, :url => {:controller => 'posts', :action => 'create'}) do |f| %>
	  <%= f.label :name %>
	  <%= f.text_field :name %>
	  <br>
	  <%= f.label :paste_content %> <br>
	  <%= f.text_area :paste_content %>
	  <br>
	  
	  <% if !session[:user_id] %>
  	  <%= f.hidden_field :user, :value => "Anonymous" %>
	  <% else %>
	  <%= f.hidden_field :user, :value => @current_user.username %>
	  <% end %>
	  <%= f.submit "Submit" %>
	<% end %>

	<% if @post.errors.any? %>
		<ul class="Signup_Errors">
			<% for message_error in @post.errors.full_messages %>
				<li>* <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>
<%= link_to "Back to home page", web_index_path %>